// components/TagList.tsx
import { Tag } from "@/types";

export const tagList: Tag[] = [
  { id: "イラスト", name: "イラスト", count: 25 },
  { id: "小説", name: "小説", count: 18 },
  { id: "イベント", name: "イベント", count: 12 },
  { id: "質問", name: "質問", count: 10 },
  { id: "Twitter", name: "Twitter", count: 10 },
  { id: "字書き", name: "字書き", count: 10 },
  { id: "愚痴", name: "愚痴", count: 10 },
  { id: "ツイッター", name: "ツイッター", count: 10 },
  { id: "支部", name: "支部", count: 10 },
  { id: "BL", name: "BL", count: 10 },
  { id: "絵描き", name: "絵描き", count: 10 },
  { id: "壁打ち", name: "壁打ち", count: 10 },
  { id: "同人誌", name: "同人誌", count: 10 },
  { id: "相談", name: "相談", count: 10 },
  { id: "雑談", name: "雑談", count: 10 },
  { id: "二次創作", name: "二次創作", count: 10 },
  { id: "漫画", name: "漫画", count: 10 },
  { id: "地雷", name: "地雷", count: 10 },
  { id: "部数", name: "部数", count: 10 },
  { id: "アンソロ", name: "アンソロ", count: 10 },
  { id: "マシュマロ", name: "マシュマロ", count: 10 },
  { id: "人間関係", name: "人間関係", count: 10 },
  { id: "感想", name: "感想", count: 10 },
  { id: "印刷所", name: "印刷所", count: 10 },
  { id: "吐き出し", name: "吐き出し", count: 10 },
  { id: "一言物申す", name: "一言物申す", count: 10 },
  { id: "悩み", name: "悩み", count: 10 },
  { id: "一次創作", name: "一次創作", count: 10 },
  { id: "同人", name: "同人", count: 10 },
    { id: "漫画家志望", name: "漫画家志望", count: 10 },
  { id: "pixiv", name: "pixiv", count: 10 },
];
